name: CI Deploy

on:
  workflow_run:
    workflows:
      - CI Build and Test
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
      contents: read

    steps:
      - name: Download Node publish artifact
        uses: actions/download-artifact@v8
        with:
          name: node-app
          path: ./publish
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Azure
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_30B7FC53F3174B04A2793DE2BC7D0F35 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_96A01072E1974D40A7C1E976C9CEB756 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EF4C4F434B07428E812445CDFC335E13 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@02a81bead70021f5284939794bcec79c271ab383 # v3.0.8
        with:
          app-name: 'retrodadsonchallenge'
          slot-name: 'Production'
          package: ./publish
